#!/bin/bash
# Generate the SSH host keys on first start, then start sshd. Idempotent:
# safe to run on every container start, and the second run is a no-op.
#
# Why the image ships no host keys: a key baked into a published image is the
# same key for everyone who pulls it, so anyone holding the image can
# impersonate the container or decrypt a session recorded against it. They are
# generated here instead, on first start, and then persist for the lifetime of
# that container (a 'docker restart' keeps them; a rebuild makes new ones).
#
# Why sshd runs as the unprivileged user: base-sandbox ships no sudo and the
# recommended runArgs drop every Linux capability, so nothing in the container
# can write /etc/ssh or switch UID. sshd only ever needs to authenticate the
# user it already runs as, which needs no privilege at all - it just needs a
# port above 1024 and its own config, keys and PID file under that user's home.
set -euo pipefail

SSHD_PORT="${SSHD_PORT:-2222}"
START_SSHD="${START_SSHD:-true}"
SSHD_BIN="${SSHD_BIN:-/usr/sbin/sshd}"

log() { echo "[sshd-init] $*"; }
warn() { echo "[sshd-init] WARNING: $*" >&2; }

if [ "${START_SSHD}" != "true" ]; then
    log "START_SSHD=${START_SSHD} - not starting sshd."
    exit 0
fi

if [ ! -x "${SSHD_BIN}" ]; then
    warn "${SSHD_BIN} is missing - skipping sshd."
    exit 0
fi

if [ "$(id -u)" -eq 0 ]; then
    # Root path: only reached when the container is deliberately started as
    # root. Keys and config live in /etc/ssh, as a distribution expects.
    mkdir -p /run/sshd
    if ! ls /etc/ssh/ssh_host_*_key > /dev/null 2>&1; then
        log "generating host keys in /etc/ssh"
        ssh-keygen -A
    fi
    mkdir -p /etc/ssh/sshd_config.d
    printf 'Port %s\n' "${SSHD_PORT}" > /etc/ssh/sshd_config.d/10-base-sandbox.conf
    if pgrep -x sshd > /dev/null 2>&1; then
        log "sshd is already running."
        exit 0
    fi
    "${SSHD_BIN}"
    log "sshd listening on port ${SSHD_PORT} (running as root)."
    exit 0
fi

SSH_DIR="${HOME}/.ssh"
HOSTKEY_DIR="${SSH_DIR}/host_keys"
CONFIG="${SSH_DIR}/sshd_config"
PIDFILE="${SSH_DIR}/sshd.pid"

mkdir -p "${HOSTKEY_DIR}"
chmod 700 "${SSH_DIR}" "${HOSTKEY_DIR}"

# One key per algorithm, generated only when absent - never regenerated, or
# every restart would trip the client's known_hosts check.
generated=false
for type in ed25519 rsa; do
    key="${HOSTKEY_DIR}/ssh_host_${type}_key"
    if [ ! -f "${key}" ]; then
        ssh-keygen -q -t "${type}" -f "${key}" -N '' -C "base-sandbox-${type}"
        chmod 600 "${key}"
        generated=true
    fi
done
if [ "${generated}" = true ]; then
    log "generated host keys in ${HOSTKEY_DIR}"
else
    log "reusing the host keys in ${HOSTKEY_DIR}"
fi

# authorized_keys must exist and be private, or a key added later by
# postCreateCommand is the only thing standing between the port and a refusal.
touch "${SSH_DIR}/authorized_keys"
chmod 600 "${SSH_DIR}/authorized_keys"

# Regenerated on every start so SSHD_PORT stays authoritative. Edit the
# generated file only for a throwaway test - it is overwritten next start.
cat > "${CONFIG}" <<CONFIG_EOF
# Generated by sshd-init.sh on every container start - edits do not survive.
Port ${SSHD_PORT}
ListenAddress 0.0.0.0
ListenAddress ::

HostKey ${HOSTKEY_DIR}/ssh_host_ed25519_key
HostKey ${HOSTKEY_DIR}/ssh_host_rsa_key
PidFile ${PIDFILE}
AuthorizedKeysFile ${SSH_DIR}/authorized_keys

# Public keys only. There is no password to guess and no PAM stack to consult -
# sshd runs unprivileged and can authenticate no account but this one.
AllowUsers ${USER:-$(id -un)}
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
UsePAM no

# StrictModes is off because the workspace bind-mount makes the home directory
# group-writable on some hosts, which sshd would otherwise refuse to start on.
StrictModes no

# Forwarding an agent or a display back out of a sandbox defeats the sandbox.
# TCP forwarding stays on: VS Code Remote-SSH and 'ssh -L' need it.
AllowAgentForwarding no
X11Forwarding no
PrintMotd no

Subsystem sftp /usr/lib/openssh/sftp-server
CONFIG_EOF
chmod 600 "${CONFIG}"

if [ -f "${PIDFILE}" ] && kill -0 "$(cat "${PIDFILE}" 2> /dev/null)" 2> /dev/null; then
    log "sshd is already running (pid $(cat "${PIDFILE}"))."
    exit 0
fi
rm -f "${PIDFILE}"

# sshd validates its config before it binds, so a failure here is a real
# configuration error and worth showing in full.
if ! "${SSHD_BIN}" -t -f "${CONFIG}"; then
    warn "the generated sshd config was rejected - sshd not started."
    exit 0
fi

if "${SSHD_BIN}" -f "${CONFIG}"; then
    log "sshd listening on port ${SSHD_PORT} as $(id -un)."
else
    warn "sshd failed to start; run '${SSHD_BIN} -Ddf ${CONFIG}' to see why."
fi
